{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-server-everything-wrong.serviceAccountName" . }}
  labels:
    {{- include "mcp-server-everything-wrong.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end -}}
